// The Farm Watcher (stand-alone, on a player's game): records what that game receives, sends and shows,
// restraints and map moves, Companion <-> bot traffic, page errors; saves a text file; never passwords.
const fs=require('fs'), path=require('path');
const { JSDOM } = require('jsdom');
const dom = new JSDOM('<!doctype html><body><div id="TextAreaChatLog"></div></body>', { url: 'https://www.bondageprojects.elementfx.com/R120/' });
const W = dom.window;
const store={}; let anyIn=null; const sent=[];
global.GM_getValue=(k,d)=>k in store?store[k]:d; global.GM_setValue=(k,v)=>store[k]=v; global.GM_registerMenuCommand=()=>{};
global.unsafeWindow=W;
W.Player={MemberNumber:221397};
W.ChatRoomData={Name:'B&B Farm',MapData:{Type:'Always'}};
W.ChatRoomCharacter=[{MemberNumber:221397,Name:'Laynie',MapData:{Pos:{X:2,Y:2}},Appearance:[]},{MemberNumber:500,Name:'Moo',MapData:{Pos:{X:5,Y:5}},Appearance:[{Group:'ItemNeck',Name:'LeatherCollar'}]}];
W.ServerSocket={on(){},onAny(f){anyIn=f;}};
W.ServerSend=(ev,d)=>sent.push([ev,d]);
const log=W.document.getElementById('TextAreaChatLog');
W.ChatRoomSendLocal=(h)=>{ const d=W.document.createElement('div'); d.innerHTML=h; log.appendChild(d); };
W.CommandCombine=()=>{};
W.__FARMWATCH_TEST__=true;
const out=(...a)=>process.stdout.write(a.join(' ')+'\n');
let fails=0; const ok=(c,msg)=>{ out(msg+' -> '+(c?'true':'false')); if(!c) fails++; };
const wait=ms=>new Promise(r=>setTimeout(r,ms));
W.eval(fs.readFileSync(path.join(__dirname,'../dist/farm-watcher.user.js'),'utf8'));
(async()=>{ await wait(1200);
  const FW=W.__farmWatch;
  ok(typeof anyIn==='function', 'it listens to everything the server sends this game');
  FW.command('start 30');
  ok(FW.state().on && FW.state().until-Date.now()>29*60000, 'start 30: recording for 30 minutes');
  anyIn('ChatRoomMessage',{Sender:260239,Type:'Whisper',Target:221397,Content:'(Your milk is at 80%, sugar.'});
  anyIn('ChatRoomMessage',{Sender:260239,Type:'Hidden',Target:221397,Content:'FarmhandMsg',Dictionary:{v:2,type:'reply',text:'STATS for Laynie'}});
  anyIn('ChatRoomMessage',{Sender:500,Type:'Activity',Content:'ChatOther-ItemPelvis-Rub',Dictionary:[{SourceCharacter:500},{TargetCharacter:221397},{FocusGroupName:'ItemPelvis'},{ActivityName:'Rub'}]});
  anyIn('ChatRoomSyncMapData',{MemberNumber:500,MapData:{Pos:{X:6,Y:5}}});
  anyIn('ChatRoomSyncMapData',{MemberNumber:500,MapData:{Pos:{X:7,Y:5}}});
  anyIn('ChatRoomSyncSingle',{Character:{MemberNumber:500,Appearance:[{Group:'ItemNeck',Name:'LeatherCollar',Property:{LockedBy:'MistressPadlock'}},{Group:'ItemArms',Name:'LeatherArmbinder',Craft:{Name:'Barn Binder'}}]}});
  anyIn('AccountBeep',{MemberNumber:260239,MemberName:'Farm Girl',Message:'Feeding time!'});
  // panel updates say what changed in them
  anyIn('ChatRoomMessage',{Sender:260239,Type:'Hidden',Target:221397,Content:'FarmhandMsg',Dictionary:{v:2,type:'state',state:{name:'Laynie',milk:{ml:1200,cap:8000},at:1}}});
  anyIn('ChatRoomMessage',{Sender:260239,Type:'Hidden',Target:221397,Content:'FarmhandMsg',Dictionary:{v:2,type:'state',state:{name:'Laynie',milk:{ml:1300,cap:8000},at:2}}});
  W.ServerSend('AccountLogin',{AccountName:'laynie_acct',Password:'hunter2'});
  W.ServerSend('ChatRoomChat',{Type:'Hidden',Target:260239,Content:'FarmhandMsg',Dictionary:{v:2,type:'cmd',text:'stats'}});
  W.ServerSend('ChatRoomChat',{Type:'Chat',Content:'hi everyone'});
  W.ChatRoomSendLocal('<div>[Farm] panel line shown only here</div>');
  const c=W.document.createElement('div'); c.textContent='Moo rubs Laynie\'s belly.'; log.appendChild(c);
  W.console.error('boom from a mod');
  FW.command('mark bot half-loaded');
  await wait(300);
  const txt=FW.fileText();
  ok(/WHISPER .*Farm|WHISPER .*260239.*80%/.test(txt), 'whispers to this player (non-Companion path)');
  ok(/FARM-IN .*reply: STATS for Laynie/.test(txt), 'farm bot -> Companion messages');
  ok(/state \(first\)/.test(txt) && /state \(changed: milk\.ml=1300\)/.test(txt), 'panel updates say what changed in them');
  ok(/FARM-OUT .*cmd: stats/.test(txt), 'Companion -> farm bot messages');
  ok(/ACTIVITY .*by Moo\(500\), on Laynie\(221397\), at ItemPelvis, activity Rub/.test(txt), 'actions, with who did what to whom');
  ok(/MOVE +Moo\(500\) → 7,5/.test(txt) && (txt.match(/MOVE +Moo/g)||[]).length===1, 'a run of steps is one line');
  ok(/ITEMS .*Moo.*MistressPadlock.*\+ItemArms: LeatherArmbinder "Barn Binder"/.test(txt), 'restraints put on and locked');
  ok(/BEEP-IN .*Feeding time/.test(txt), 'beeps');
  ok(/SENT +\[Chat\]: hi everyone/.test(txt), "what this player sends");
  ok(/LOCAL +\[Farm\] panel line/.test(txt), 'lines shown only on this screen');
  ok(/SHOWN +Moo rubs Laynie/.test(txt), 'what appeared in the chat log');
  ok(/ERROR +boom from a mod/.test(txt), 'errors on the page');
  ok(/MARK +★ bot half-loaded/.test(txt), '/watch mark');
  ok(!/hunter2|laynie_acct/.test(txt), 'never the password or account name');
  ok(/^B&B Farm — Farm Watcher recording/.test(txt) && /WEARING +Moo\(500\) · ItemNeck: LeatherCollar/.test(txt), 'a header, and what everyone had on at the start');
  // a reload carries on
  await wait(100); FW.command('stop');
  ok(!FW.state().on && /stopped \(stopped by hand\)/.test(FW.fileText()), 'stop');
  out(fails ? fails+' FAILED' : 'ALL PASSED'); process.exit(fails?1:0);
})();
